apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pocketbase.fullname" . }}-pvc
  labels:
    app.kubernetes.io/name: pocketbase
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}