{{- if .Values.token.createFromValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- if .Values.token.secretName }}{{ .Values.token.secretName }}{{- else }}{{ include "pocketbase.fullname" . }}-token{{- end }}
  labels:
    app.kubernetes.io/name: pocketbase
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  token: "{{ .Values.token.value }}"
{{- end }}