apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocketbase.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: pocketbase
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  email: "{{ .Values.admin.email }}"
  password: "{{ .Values.admin.password }}"