# Default values for pocketbase.
# Reference via Helm: `.Values.image.repository`, `.Values.persistence.size`, etc.
replicaCount: 1

image:
  repository: ghcr.io/pocketbase/pocketbase
  tag: "0.14.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: ""
  mountPath: /pb_data

admin:
  # initial admin credentials (can be overridden via secret)
  email: admin@example.com
  password: changeme

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

readinessProbe:
  path: /
  port: 8090
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /
  port: 8090
  initialDelaySeconds: 15
  periodSeconds: 20