# Default values for pocketbase.
# Reference via Helm: `.Values.image.repository`, `.Values.persistence.size`, etc.
replicaCount: 1

image:
  repository: docker.io/pocketbase/pocketbase
  tag: "0.14.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: ""
  mountPath: /pb_data

admin:
  # initial admin credentials (can be overridden via secret)
  email: admin@example.com
  password: changeme

# Token creation settings
# If token.createFromValues is true and token.value is provided, the chart will render a token secret.
# Otherwise the Helm hook job can create the token dynamically (recommended).
token:
  # If true and token.value is non-empty, the chart will create a Secret with the token.
  createFromValues: false
  # literal token value (use only for bootstrapping / CI; avoid putting long-lived secrets here)
  value: ""
  # optional explicit secret name to create/use; if empty the job will create a sensible name
  secretName: ""

  # Job settings when using the Helm hook to create tokens
  job:
    enabled: true
    image: bitnami/kubectl:1.27.3
    backoffLimit: 3
    # how many attempts to wait for pocketbase readiness
    retries: 30
    sleepSeconds: 2

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

readinessProbe:
  path: /
  port: 8090
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /
  port: 8090
  initialDelaySeconds: 15
  periodSeconds: 20