version: 2
project_name: shisha-tracker-nextgen-frontend

# HARTES Abschalten der Go-Builds
builds:
  - id: no-go-build
    # irgendein Fake-Main, damit nichts gebaut werden kann
    main: ./__no_go_main__.go
    goos: []        # keine Targets -> es wird nichts gebaut
    goarch: []      # dito

dist: dist-release

before:
  hooks:
    - npm ci
    - npm run build

archives:
  - id: frontend-dist
    meta: true
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    files:
      - dist/**/*
    wrap_in_directory: true

dockers_v2:
  - images:
      - ghcr.io/str33tr4z0r/shisha-tracker-nextgen-frontend
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    platforms:
      - linux/amd64
    dockerfile: Frontend.goreleaser
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "https://github.com/str33tr4z0r/shisha-tracker-nextgen"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"