version: 2
project_name: shisha-tracker-nextgen-frontend

builds: []
dist: dist-release

before:
  hooks:
    - npm ci
    - npm run build

archives:
  - id: frontend-dist
    meta: true
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    files:
      - dist/**/*
    wrap_in_directory: true

dockers_v2:
  - images:
      - ghcr.io/str33tr4z0r/shisha-tracker-nextgen-frontend
    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    platforms:
      - linux/amd64
    dockerfile: Frontend.goreleaser
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.source: "https://github.com/str33tr4z0r/shisha-tracker-nextgen"
    # build_args: {}   # <- nur falls du ARGs brauchst
    # flags: []        # <- nur falls du wirklich buildx-Flags im Format --flag=value brauchst

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"