apiVersion: apps/v1
kind: Deployment
metadata:
  name: shisha-backend-mock
  namespace: shisha
  labels:
    app: shisha-backend-mock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shisha-backend-mock
  template:
    metadata:
      labels:
        app: shisha-backend-mock
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    app: shisha-backend-mock
      containers:
        - name: backend-mock
          image: ghcr.io/str33tr4z0r/shisha-tracker-nextgen-backend:latest
          imagePullPolicy: Always
          env:
            - name: STORAGE
              value: "couchdb"
            - name: COUCHDB_URL
              value: "http://shisha-couchdb:5984"
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: shisha-couchdb-admin
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shisha-couchdb-admin
                  key: password
            - name: COUCHDB_DB
              value: "shisha"
            - name: SKIP_MIGRATIONS
              value: "false"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: shisha-backend-mock
  namespace: shisha
  labels:
    app: shisha-backend-mock
spec:
  type: ClusterIP
  selector:
    app: shisha-backend-mock
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
# Secret pocketbase-admin removed — erstelle dieses Secret manuell falls benötigt.
# Beispiel:
# kubectl create secret generic pocketbase-admin \
#   --from-literal=email=admin@example.com \
#   --from-literal=password=changeme \
#   -n shisha