version: "3.8"
 
services:
  couchdb:
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpassword
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      - "5984:5984"
    restart: unless-stopped
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - STORAGE=couchdb
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_DATABASE=shisha
    ports:
      - "8080:8080"
    depends_on:
      - couchdb
    restart: unless-stopped
    # If the backend binary listens on a different port, adjust above.
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
 
volumes:
  couchdb_data: