version: "3.8"

services:
  pocketbase:
    image: pocketbase/pocketbase:0.17.2
    command: ["serve", "--http=0.0.0.0:8090", "--dir", "/pb_data"]
    volumes:
      - pb_data:/pb_data
    ports:
      - "8090:8090"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - STORAGE=pb
      - POCKETBASE_URL=http://pocketbase:8090
    ports:
      - "8080:8080"
    depends_on:
      - pocketbase
    restart: unless-stopped
    # If the backend binary listens on a different port, adjust above.

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pb_data: