# ClusterIP Service für interne Erreichbarkeit von CouchDB (Port 5984)
# Deutsch: Name auf "shisha-couchdb" geändert, damit bestehende Anwendungen (COUCHDB_URL=http://shisha-couchdb:5984) DNS auflösen.
apiVersion: v1
kind: Service
metadata:
  name: shisha-couchdb
  namespace: shisha
  labels:
    app: couchdb
spec:
  type: ClusterIP
  selector:
    app: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: 5984
      protocol: TCP