# NetworkPolicy: Beschränkt Verkehr auf CouchDB-spezifische Ports innerhalb des Namespaces.
# Deutsch: Erlaubt nur eingehenden Traffic auf 5984 (HTTP), 4369 (epmd) und 9100-9105 (Erlang Distribution)
# von Pods im gleichen Namespace. Zusätzlich werden DNS- und Kubernetes-API-Egress-Regeln
# hinzugefügt, damit die Sidecar-Discovery (getent / K8s API) funktioniert.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-couchdb-comm
  namespace: shisha
  labels:
    app: couchdb
spec:
  podSelector:
    matchLabels:
      app: couchdb
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        # Erlaube Zugriff von allen Pods im selben Namespace (shisha)
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5984
        - protocol: TCP
          port: 4369
        - protocol: TCP
          port: 9100
        - protocol: TCP
          port: 9101
        - protocol: TCP
          port: 9102
        - protocol: TCP
          port: 9103
        - protocol: TCP
          port: 9104
        - protocol: TCP
          port: 9105
  egress:
    # 1) DNS + Kubernetes API: erlauben, damit Sidecar DNS-Lookups (kube-dns) und
    #    die K8s API (kubernetes.default.svc:443) für Pod-IP-Abfragen funktionieren.
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
    # 2) Inter-Pod Kommunikation im Namespace für CouchDB / Erlang Ports
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5984
        - protocol: TCP
          port: 4369
        - protocol: TCP
          port: 9100
        - protocol: TCP
          port: 9101
        - protocol: TCP
          port: 9102
        - protocol: TCP
          port: 9103
        - protocol: TCP
          port: 9104
        - protocol: TCP
          port: 9105

# Optional: Wenn Sie Zugriff vom Ingress-Controller benötigen, entkommentieren Sie folgendes Beispiel und passen den Namespace/Label an.
# - from:
#     - namespaceSelector:
#         matchLabels:
#           app.kubernetes.io/name: ingress-nginx
#       podSelector:
#         matchLabels:
#           app.kubernetes.io/component: controller