apiVersion: v1
kind: Service
metadata:
  name: {{ include "cockroachdb.fullname" . }}
  labels:
    app: {{ include "cockroachdb.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 26257
      protocol: TCP
      targetPort: 26257
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ include "cockroachdb.name" . }}