apiVersion: v1
kind: ServiceAccount
metadata:
  name: shisha-backend-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shisha-backend-leader-role
  namespace: default
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch", "delete", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shisha-backend-leader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: shisha-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: shisha-backend-leader-role
  apiGroup: rbac.authorization.k8s.io