apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: couchdb-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters: {}