apiVersion: v1
kind: PersistentVolume
metadata:
  name: shisha-couchdb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/shisha/couchdb
    type: DirectoryOrCreate