apiVersion: v1
kind: PersistentVolume
metadata:
  name: shisha-couchdb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "couchdb-storage-class"
  claimRef:
    namespace: shisha
    name: couchdb-data-shisha-couchdb-0
  hostPath:
    path: /var/lib/shisha/couchdb
    type: DirectoryOrCreate