apiVersion: v1
kind: ConfigMap
metadata:
  name: shisha-couchdb-seed-deprecated
  namespace: shisha
data:
  note: |
    The original shisha-couchdb-seed Job has been deprecated.
    Database creation and index setup are now handled by the initContainer in k8s/couchdb.yaml.
    If you need to run a one-off seed, use the archived manifest in archive/ or create a manual job.
    This ConfigMap retains the original Job contents for reference.