apiVersion: v1
kind: ConfigMap
metadata:
  name: shisha-couchdb-seed-config
  namespace: shisha
data:
  shishas: |
    {"name":"Double Apple","flavor":"Double Apple","manufacturer":{"name":"Al Fakher"}}
    {"name":"Mint","flavor":"Mint","manufacturer":{"name":"Al Fakher"}}
    {"name":"Blueberry","flavor":"Blueberry","manufacturer":{"name":"Adalya"}}
    {"name":"Love 66","flavor":"Love 66","manufacturer":{"name":"Adalya"}}
    {"name":"White Gummi Bear","flavor":"White Gummi Bear","manufacturer":{"name":"Fumari"}}
    {"name":"Blue Mist","flavor":"Blue Mist","manufacturer":{"name":"Starbuzz"}}
    {"name":"Lemon Mint","flavor":"Lemon Mint","manufacturer":{"name":"Al Waha"}}
    {"name":"Mango","flavor":"Mango","manufacturer":{"name":"Mazaya"}}
    {"name":"Ice Lemon","flavor":"Ice Lemon","manufacturer":{"name":"187 Tobacco"}}
    {"name":"Peach","flavor":"Peach","manufacturer":{"name":"Al Fakher"}}