apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shisha-couchdb-hpa
  namespace: shisha
  labels:
    app: shisha-couchdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: shisha-couchdb
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80