apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shisha-cockroachdb-hpa
  labels:
    app: shisha-cockroachdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: shisha-cockroachdb
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50