apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shisha-frontend-hpa
  namespace: shisha
  labels:
    app: shisha-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shisha-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50