apiVersion: batch/v1
kind: Job
metadata:
  name: shisha-couchdb-init
  namespace: shisha
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        job: shisha-couchdb-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: curlimages/curl:8.1.2
          env:
            - name: COUCHDB_URL
              value: "http://shisha-couchdb:5984"
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: shisha-couchdb-admin
                  key: username
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shisha-couchdb-admin
                  key: password
            - name: COUCHDB_DB
              value: "shisha"
          command:
            - /bin/sh
            - -c
            - |
              set -eu
              echo "waiting for couchdb..."
              until curl -sSf "$COUCHDB_URL/"; do
                sleep 2
              done
              echo "creating database $COUCHDB_DB (if not exists)"
              curl -sS -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X PUT "$COUCHDB_URL/$COUCHDB_DB" || true
              echo "creating index idx_type_id"
              curl -sS -u "$COUCHDB_USER:$COUCHDB_PASSWORD" -X POST "$COUCHDB_URL/$COUCHDB_DB/_index" -H "Content-Type: application/json" -d '{"index":{"fields":["type","id"]},"name":"idx_type_id","type":"json"}' || true
      restartPolicy: Never