# PocketBase token job manifest removed and archived.
# Original content moved to: archive/pocketbase/k8s-pocketbase-token-job.yaml
# Removed from active manifests on 2025-09-15.
# If you need to restore, copy the archived file back to this path.