apiVersion: v1
kind: Service
metadata:
  name: {{ include "shisha-frontend.fullname" . }}
  labels:
    {{- include "shisha-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "shisha-frontend.name" . }}