apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shisha-pocketbase-pvc
  namespace: shisha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shisha-pocketbase
  namespace: shisha
  labels:
    app: shisha-pocketbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shisha-pocketbase
  template:
    metadata:
      labels:
        app: shisha-pocketbase
    spec:
      # pod-level security and fs group to ensure mounted PVC is writable by UID 1000
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      # Ensure correct ownership of the mounted PVC before container starts
      initContainers:
        - name: init-chown-pbdata
          image: busybox:1.36
          command: ["/bin/sh","-c","chown -R 1000:1000 /pb_data || true"]
          volumeMounts:
            - name: pb-data
              mountPath: /pb_data
      containers:
        - name: pocketbase
          image: docker.io/elestio/pocketbase:v0.30.0
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
            runAsNonRoot: true
            runAsUser: 1000
          command: ["pocketbase","serve","--http=0.0.0.0:8090","--dir","/pb_data"]
          ports:
            - containerPort: 8090
              name: http
          volumeMounts:
            - name: pb-data
              mountPath: /pb_data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /_/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_/
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 6
      volumes:
        - name: pb-data
          persistentVolumeClaim:
            claimName: shisha-pocketbase-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shisha-pocketbase
  namespace: shisha
  labels:
    app: shisha-pocketbase
spec:
  type: ClusterIP
  selector:
    app: shisha-pocketbase
  ports:
    - name: http
      port: 8090
      targetPort: http
---