# PodDisruptionBudget sorgt dafür, dass mindestens 1 Pod verfügbar bleibt beim Rolling/Manuellen Eingriff.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: couchdb-pdb
  namespace: shisha
  labels:
    app: couchdb
spec:
  # Akzeptanzkriterium: minAvailable: 1 verhindert, dass der Cluster unter 1 Pod fällt.
  minAvailable: 1
  selector:
    matchLabels:
      app: couchdb