fullnameOverride: shisha-backend-mock
replicaCount: 3
image:
  repository: ricardohdc/shisha-tracker-nextgen-backend-mock
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: shisha-backend.local
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 20
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
metrics:
  enabled: true
  path: /api/metrics
env:
  # Storage selection for backend: "couchdb" (default) or "gorm" (legacy)
  storage:
    mode: couchdb
    couchdb:
      # CouchDB URL used by backend when storage.mode == "couchdb"
      url: http://couchdb:5984
      # database name used by backend
      database: shisha
      # optional admin credentials secret name (backend will read username from COUCHDB_USER and password from secret)
      adminSecretName: couchdb-admin
  # SQL database settings (legacy GORM backend); keep defaults for deployments that still use SQL
  database:
    host: postgres
    port: "5432"
    name: shisha
    user: postgres
    passwordSecret: postgres-password
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - shisha-backend-mock
        topologyKey: kubernetes.io/hostname
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
resourcesEnabled: true