fullnameOverride: shisha-backend-mock
replicaCount: 3
image:
  repository: shisha-tracker-nextgen-backend-mock
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: shisha-backend.local
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 20
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
metrics:
  enabled: true
  path: /api/metrics
env:
  database:
    host: shisha-cockroachdb
    port: 26257
    name: shisha
    user: root
    passwordSecret: cockroachdb-root
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - shisha-backend-mock
        topologyKey: kubernetes.io/hostname
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
resourcesEnabled: true