fullnameOverride: shisha-backend-mock
replicaCount: 3
image:
  repository: ricardohdc/shisha-tracker-nextgen-backend-mock
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: regcred
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: shisha-backend.local
      paths:
        - path: /
          pathType: Prefix
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 20
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /api/healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
metrics:
  enabled: true
  path: /api/metrics
env:
  # Storage selection for backend: "pb" (PocketBase) or "gorm" (legacy)
  storage:
    mode: pb
    pocketbase:
      # POCKETBASE URL used by backend when storage.mode == "pb"
      url: http://pocketbase:8090
      # optional admin credentials secret name (if backend needs to call admin endpoints)
      adminSecretName: pocketbase-admin
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - shisha-backend-mock
        topologyKey: kubernetes.io/hostname
rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
resourcesEnabled: true