# Secret mit Admin-Credentials und ERLANG_COOKIE
# Achtung: In Produktionsumgebungen Werte ersetzen oder ein externes Secret-Backend verwenden.
apiVersion: v1
kind: Secret
metadata:
  name: shisha-couchdb-admin
  namespace: shisha
  labels:
    app: shisha-couchdb
type: Opaque
# stringData erleichtert das Anwenden von Klartext-Werten (kubectl konvertiert in base64)
stringData:
  COUCHDB_USER: "shisha_admin"
  COUCHDB_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"
  ERLANG_COOKIE: "REPLACE_WITH_ERLANG_COOKIE"
# Sicherheit: Entfernen Sie Beispiel-/Defaultwerte vor dem Deploy in Produktion.