# RBAC für Sidecar: Lesezugriff auf Pods/Endpoints/Services/ConfigMaps im Namespace (readonly)
# Deutsch: Wird benötigt, falls der Sidecar die K8s-API zur Erkennung von Peers oder Health-Checks verwendet.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchdb-sa
  namespace: shisha
  labels:
    app: couchdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: couchdb-sidecar-reader
  namespace: shisha
rules:
  - apiGroups: [""]
    resources:
      - pods
      - endpoints
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: couchdb-sidecar-reader-binding
  namespace: shisha
subjects:
  - kind: ServiceAccount
    name: couchdb-sa
    namespace: shisha
roleRef:
  kind: Role
  name: couchdb-sidecar-reader
  apiGroup: rbac.authorization.k8s.io