name: Frontend Build and Release

on:
  push:
    tags:
      - '*'   # z.B. v1.2.3


permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Removed host-side pnpm install and dependency installation.
      # The frontend Dockerfile runs `npm ci`/`npm install` during image build,
      # so installing node modules on the runner creates changes in the workspace
      # that make git appear "dirty" to GoReleaser.
      # If you prefer installing on the runner, run it inside a clean temp dir
      # or ensure you `git clean -ffdx frontend` before goreleaser runs.

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
          workdir: frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          GITHUB_REPOSITORY: ${{ github.repository }}

