name: Backend Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (mit Tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'     # oder deine reale Version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (für buildx)
        uses: docker/setup-qemu-action@v3

      - name: Validate GoReleaser config
        run: goreleaser check --config .goreleaser.yaml
        working-directory: backend

      - name: Validate GoReleaser config (Backend)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: check --config .goreleaser.yaml
          workdir: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          GITHUB_REPOSITORY: ${{ github.repository }}